### ISSUE TITLE
Implement logic to fetch a list of movies from GPT based on provided criteria

### ISSUE THREAD

**Issue by forkball** [forkball/on-deck#2]
The idea here is that we take input from the user on more qualitative aspects of what they enjoy/want to watch in a film and get GPT to generate a list in a format that we can manipulate.

**Tasks**

- [ ] Establish a connection to the GPT Api and determine the different tiers offered
- [ ] Format the GPT responses so that they provide a useable format 
- [ ] Setup a simple landing page where users can input criteria and get a GPT response back
